# File: .github/workflows/nodejs-backend.yml

name: Node.js CI - Back-end

on:
  push:
    paths:
      - 'back-end/**'
  pull_request:
    paths:
      - 'back-end/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: back-end/package-lock.json

      - name: Install dependencies
        working-directory: back-end
        run: npm ci

      - name: Build (if any)
        working-directory: back-end
        run: npm run build --if-present

      - name: Run tests
        working-directory: back-end
        run: npm test
