# File: .github/workflows/nodejs-frontend.yml

name: Node.js CI - Front-end

on:
  push:
    paths:
      - 'front-end/**'
  pull_request:
    paths:
      - 'front-end/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: front-end/package-lock.json

      - name: Install dependencies
        working-directory: front-end
        run: npm ci

      - name: Build front-end
        working-directory: front-end
        run: npm run build

      - name: Run tests
        working-directory: front-end
        run: npm test
