name: Node.js CI for Frontend & Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: front-end

      - name: Build Frontend
        run: npm run build --if-present
        working-directory: front-end

      - name: Test Frontend
        run: npm test
        working-directory: front-end

  build-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Backend Dependencies
        run: npm ci
        working-directory: back-end

      - name: Build Backend
        run: npm run build --if-present
        working-directory: back-end

      - name: Test Backend
        run: npm test
        working-directory: back-end
